### ISSUE TITLE
US collaborators with data issues needed

### ISSUE THREAD

**Issue by paul-wegener** [Daniel-Mietchen/open-science-prize#1]
Integrator Software can join databases, provide an interface for complex queries, manage the data using standardized ontologies - this is the tech to enable all the wonders of Open Science. We want a collaborator in the US to demonstrate the technology for the Open Science Prize. You will get a functioning application on the web to access any collection of data you have and share it with the world. The system will integrate data from others. We are a start-up in Nova Scotia. Contact me for details and a demo. Paul Wegener pwegener (at) epitomepharm (dot) com

**Comment by Daniel-Mietchen** [comment]
Thanks - I put it in: https://github.com/Daniel-Mietchen/open-science-prize/commit/34d99a9c3abb9853d48347243a8b8d22cf3508c4 and [tweeted it](https://twitter.com/EvoMRI/status/675511036422787072).

**Comment by paul-wegener** [comment]
Dear Daniel, 

Thanks for posting this. It got a bit garbled in the process, understandably. My address is Epitome Pharmaceuticals, but the post comes from a start-up Integrator Software. Please change the project to "data integration across silos" and the abstract to "US collaborators with data issues needed for Open Science Prize." 

Thanks for maintaining this site. I am sure activity will go up as the deadline approaches.

With regards and happy holidays, Paul T. Wegener

(212) 882-1788

**Comment by Daniel-Mietchen** [comment]
@paul-wegener I updated your entry and also added your contact details as stated in this thread. Please let us know in case you found a collaborator.

**Comment by Daniel-Mietchen** [comment]
Closing now, since the submission deadline has passed. If anyone has found a collaborator this way, I would appreciate notice nonetheless.
