### ISSUE TITLE
How to organize open discussion of all ideas? 

### ISSUE THREAD

**Issue by RomanGurinovich** [Daniel-Mietchen/open-science-prize#7]
Dear colleagues, 

we recognize this challenge as a chance to improve global science performance. So it goes far beyond business goals and addresses common interests. 

For example, our team is going to apply with long term vision and single data exchange platform as practical phase I. Feedback from committee, knowing how we can partner with colleagues, aligning proposition with current scope of nih.gov would make specification development much more efficient. 

**May we propose preliminary webex with all interested parties, including NIH, WellcomeTrust, applicants, scientists and pharma reps to discuss ideas that we all have right now?** Most likely all participants have bright ideas and we can build very strong solutions all together 

Best regards,
Roman, Infinity team

**Comment by BorderCloud** [comment]
Hello

I am ready to discuss. 
My email is : karima.rafes@gmail.com

Best regards,
Karima
http://www.bordercloud.com/

**Comment by Daniel-Mietchen** [comment]
Closing this, since the competition is over for now. Feel free to make suggestions over at https://github.com/Daniel-Mietchen/open-science-prize/blob/master/feedback.md on how the matchmaking could be improved should there be anything similar in the future.
